LLPInternship/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.views.static import serve

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls'), name='core'),
]

urlpatterns += static(settings.MEDIA_URL,
                      document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL,
                      document_root=settings.STATIC_ROOT)

core/urls.py
from django.urls import path
from core.views import *


app_name = 'core'

urlpatterns = [
    path('', LoginView.as_view(), name='home'),
    path('user-register/', UserRegistrationView.as_view(), name='user-register'),
    path('user-home', UserHomeView.as_view(), name='user-home'),
    path('user-logout', userLogout, name='user-logout'),

]

core/models.py
from django.db import models
from django.contrib.auth.models import PermissionsMixin
from django.contrib.auth.base_user import AbstractBaseUser
from .managers import UserManager

# Create your models here.



GENDER = (
    ("Male", "Male"),
    ("Female", "Female"),
    ("Other", "Other"),
)


class User(AbstractBaseUser, PermissionsMixin):
    username = models.CharField(max_length=10, null=True, blank=True)
    email = models.EmailField(unique=True)
    fullname = models.CharField(max_length=60, null=True)
    state = models.TextField(max_length=200, null=True)
    country = models.CharField(max_length=100, null=True)
    pincode = models.IntegerField(null=True)
    gender = models.CharField(max_length=12, choices=GENDER)
    is_staff = models.BooleanField(default=False)
    objects = UserManager()

    USERNAME_FIELD = 'email'
    # REQUIRED_FIELDS = ['first_name', 'last_name']

core/forms.py
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm
from django import forms
from .models import *


class UserRegistrationForm(UserCreationForm, forms.Form):
	fullname = forms.CharField(label='Full Name')
	state = forms.CharField(label='State')
	country = forms.CharField(label='Country')
	pincode = forms.CharField(label='Pincode')

	class Meta:
		model = User
		fields = ['fullname', 'email', 'password1', 'password2', 'state', 'country', 'pincode', 'gender']


class UserLoginForm(forms.Form):
    email = forms.EmailField(label='Email')
    password = forms.CharField(widget=forms.PasswordInput())

core/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.views.generic import CreateView, TemplateView
from django.contrib.auth import authenticate, login, logout
from .forms import *


# Create your views here.


class UserRegistrationView(CreateView):
    form_class = UserRegistrationForm
    initial = {'key': 'value'}
    template_name = 'user_register.html'

    def get(self, request, *args, **kwargs):
        form = self.form_class(initial=self.initial)
        return render(request, self.template_name, {'form': form})

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            form.save()
            # username = form.cleaned_data.get('username')
            email = form.cleaned_data.get('email')
            messages.success(request, 'Account was created for ' + email)
            return redirect('core:user-register')
        return render(request, self.template_name, {'form': form})


class LoginView(TemplateView):
    form_class = UserLoginForm
    initial = {'key': 'value'}
    template_name = 'login.html'

    def get(self, request, *args, **kwargs):
        form = self.form_class(initial=self.initial)
        return render(request, self.template_name, {'form': form})

    def post(self, request, *args, **kwargs):
    	form = self.form_class(request.POST)
    	email = request.POST['email']
    	password = request.POST['password']
    	user = authenticate(request, email=email, password=password)
    	if user is not None:
    		login(request, user)
    		return redirect('core:user-home')
    	else:
    		messages.info(request, 'Username OR Password is Incorrect')
    	return render(request, self.template_name, {'form': form})


def userLogout(request):
    logout(request)
    return redirect('core:home')


class UserHomeView(TemplateView):
    template_name = 'user_home.html'

core/templates/home.html
{% extends 'core/main.html' %}
{% block title %}Home{% endblock %}
{% load static%}


{% block content %}



{% endblock %}

core/templates/login.html
{% extends 'main.html' %}
{% block title %}Login{% endblock %}

{% block content %}
{% if messages %}
    <div class="alert alert-success">
        {% for message in messages %}
            {{ message }}
        {% endfor %}
    </div>
{% endif %}
<div class="container">

    <form action="{% url 'core:home' %}" method="POST">

        {% csrf_token %}
        {% for field in form %}
            {% for error in field.errors %}
                <div class="alert alert-danger">
                    <strong>{{ error }}</strong>
                </div>
            {% endfor %}

            {% for error in field.non_field_errors %}
                <div class="alert alert-danger">
                    <strong>{{ error }}</strong>
                </div>
            {% endfor %}
            <p>
                {{ field.label_tag }}
                {{ field }}
                {% if field.help_text %}
                    <small style="color: tomato">{{ field.help_text }}</small>
                {% endif %}

            </p>
        {% endfor %}
        <input type="reset" class="btn btn-block btn-danger">
        <input type="submit" class="btn btn-block btn-primary">

    </form>
</div>

{% endblock %}

core/templates/main.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% load static %}
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
    <script src="{% static 'bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
</head>

<body>
    {% include 'navbar.html' %}
    <br><br><br>
    <!div class="container">
        {% block content %}

        {% endblock %}
    <!/div>


</body>
</html>

core/templates/navbar.html
{% load static %}

<nav class="navbar navbar-expand-lg fixed-top navbar-dark bg-dark" >
  <a class="navbar-brand" href="#">LLP Internship</a>
  <button class="navbar-toggler collapsed" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar-nav">
        <a class="nav-item nav-link active" href="{% url 'core:home' %}">Home</a>
        {% if request.user.is_authenticated %}
          <a class="btn btn-outline-warning" href="{% url 'core:user-logout' %}">Logout</a>&nbsp;

        {% else %}  
        <a class="btn btn-outline-warning" href="{% url 'core:home' %}">Login</a>&nbsp;&nbsp;
        <a class="btn btn-outline-primary" href="{% url 'core:user-register' %}">Register</a>&nbsp;
        {% endif %}
    </div>
  </div>
</nav>

core/templates/user_home.html
{% extends 'main.html' %}
{% block title %}Home{% endblock %}

{% block content %}
<h1>Welcome {{ request.user.fullname }}</h1>

{% endblock %}

core/templates/user_register.html
{% extends 'main.html' %}
{% block title %}Register{% endblock %}

{% block content %}
<div class="container">
    <form action="{% url 'core:user-register' %}" method="POST">

        {% csrf_token %}
        {% for field in form %}
            {% for error in field.errors %}
                <div class="alert alert-danger">
                    <strong>{{ error }}</strong>
                </div>
            {% endfor %}

            {% for error in field.non_field_errors %}
                <div class="alert alert-danger">
                    <strong>{{ error }}</strong>
                </div>
            {% endfor %}
            <p>
                {{ field.label_tag }}
                {{ field }}
                {% if field.help_text %}
                    <small style="color: tomato">{{ field.help_text }}</small>
                {% endif %}

            </p>
        {% endfor %}
        <input type="reset" class="btn btn-block btn-danger">
        <input type="submit" class="btn btn-block btn-primary">

    </form>
</div>
{% endblock %}